pipelines:
  my_pipeline:
    input:
      type: http
      settings:
        port: 8081
        tls:
          enable: true
          allow_unsigned: true
        auth:
          method: "secret"
          secret: "sha1=helloworld"
        events: ["upload"]
        max_upload_size: "5G"
    save:
      type: file
      settings:
        path: "/tmp/upload"
        filename: "myfile-{{input.body.version}}.zip"
        create: true
        chown: "root:www-data"
        chmod: 750
      subscribe:
        - component: input
    execute:
      type: bash
      settings:
        pwd: "/data"
        command: "./deploy.sh"
        arguments:
          - "{{save.filename}} {{input.body.version}}"
      subscribe:
        - component: input
        - component: save